package defpackage;

public class ix {
    public static String aa = "Select";
    public static String ab = "Loading sprites - ";
    public static String ac = "Take";
    public static String ad = "Loaded config";
    public static String ae = "Starting game engine...";
    public static String af = "Prepared sound engine";
    public static String ag = "Loaded title screen";
    public static String ah = "for 30 days: ";
    public static String ai = "Loading - please wait.";
    public static String aj = "Members object";
    public static String ak = "Continue";
    public static String al = "Connecting to update server";
    public static String am = "Please wait - attempting to reestablish";
    public static String an = "Drop";
    public static String ao = "Ok";
    public static String ap = "Discard";
    public static String aq = "Hidden";
    public static String ar = "Loading config - ";
    public static String as = "Prepared visibility map";
    public static String at = "Trust this computer";
    public static String au = "Loading fonts - ";
    public static String av = "Loaded fonts";
    public static String aw = "Connection lost";
    public static String ax = "Loaded update list";
    public static String ay = "Loading title screen - ";
    public static String az = "Checking for updates - ";
    public static String ba = "Please try using a different world.";
    public static String bb = "Loading interfaces - ";
    public static String bc = "Please try using a different world.";
    public static String bd = "Loading world map - ";
    public static String be = "";
    public static String bf = "Your account has been disabled.";
    public static String bg = "No response from server.";
    public static String bh = "Loaded textures";
    public static String bi = "Please enter a 6-digit PIN.";
    public static String bj = "Connection timed out.";
    public static String bk = "";
    public static String bl = "Please check your message-centre for details.";
    public static String bm = "Loading textures - ";
    public static String bn = "";
    public static String bo = "You have only just left another world.";
    public static String bp = "Loaded sprites";
    public static String bq = " seconds.";
    public static String br = "Loaded wordpack";
    public static String bs = "";
    public static String bt = "Loading wordpack - ";
    public static String bu = "Loaded interfaces";
    public static String bv = "";
    public static String bw = "Error connecting to server.";
    public static String bx = "";
    public static String by = "Loaded world map";
    public static String bz = "Your profile will be transferred in:";
    public static String ca = "";
    public static String cb = "";
    public static String cc = "RuneScape has been updated!";
    public static String cd = "";
    public static String ce = "";
    public static String cf = "Please reload this page.";
    public static String cg = "";
    public static String ch = "Login limit exceeded.";
    public static String ci = "Too many connections from your address.";
    public static String cj = "Could not complete login.";
    public static String ck = "Login server offline.";
    public static String cl = "session or the server is too busy right now.";
    public static String cm = "Unable to connect.";
    public static String cn = "Please subscribe, or use a different world.";
    public static String co = "Please try again in a few minutes.";
    public static String cp = "Please use a different world.";
    public static String cq = "";
    public static String cr = "This world is full.";
    public static String cs = "We suspect someone knows your password.";
    public static String ct = "";
    public static String cu = "Bad session id.";
    public static String cv = "Unable to connect.";
    public static String cw = "You need a members account to login to this world.";
    public static String cx = "Press 'change your password' on front page.";
    public static String cy = "Your account has not logged out from its last";
    public static String cz = "";
    public static String da = "";
    public static String db = "The server is being updated.";
    public static String dc = "";
    public static String dd = "You are standing in a members-only area.";
    public static String de = "";
    public static String df = "No reply from loginserver.";
    public static String dg = "";
    public static String dh = "";
    public static String di = "Account locked as we suspect it has been stolen.";
    public static String dj = "Invalid loginserver requested.";
    public static String dk = "Please try using a different world.";
    public static String dl = "Please wait 1 minute and try again.";
    public static String dm = "";
    public static String dn = "Please try again.";
    public static String do = "Please use a different world.";
    public static String dp = "Please wait a few minutes before trying again.";
    public static String dq = "This world is running a closed Beta.";
    public static String dr = "";
    public static String ds = "To play on this world move to a free area first";
    public static String dt = "Sorry invited players only.";
    public static String du = "Malformed login packet.";
    public static String dv = "";
    public static String dw = "Press 'recover a locked account' on front page.";
    public static String dx = "Too many login attempts.";
    public static String dy = "Please wait 1 minute and try again.";
    public static String dz = "Please try using a different world.";
    public static String ea = "";
    public static String eb = "as it was used to break our rules.";
    public static String ec = "";
    public static String ed = "";
    public static String ee = "";
    public static String ef = "Your account is currently inaccessible.";
    public static String eg = "via the website, or the main game.";
    public static String eh = "";
    public static String ei = "Error loading your profile.";
    public static String ej = "Please try using a different world.";
    public static String ek = "This computers address has been blocked";
    public static String el = "";
    public static String em = "Your account must have a displayname set";
    public static String en = "unsuccessful.  Don't worry, you can sort";
    public static String eo = "Your attempt to log into your account was";
    public static String ep = "Unexpected loginserver response.";
    public static String eq = "Please contact customer support.";
    public static String er = "Please enter your password.";
    public static String es = "Please try again in a few minutes.";
    public static String et = "Please enter your username/email address.";
    public static String eu = "";
    public static String ev = "this out by visiting the billing system.";
    public static String ew = "in order to play the game.  Please set it";
    public static String ex = "";
    public static String ey = "Service unavailable.";
    public static String ez = "";
    public static String fa = "level-";
    public static String fb = " has logged in.";
    public static String fc = " has logged out.";
    public static String fd = "Sorry, but your account is not eligible to";
    public static String fe = "Unexpected server response";
    public static String ff = "";
    public static String fg = "Attack";
    public static String fh = "playing the main game instead!";
    public static String fi = "You need to vote to play!";
    public static String fj = "";
    public static String fk = "The code you entered was incorrect.";
    public static String fl = "and then come back here!";
    public static String fm = "";
    public static String fn = "Visit runescape.com and vote,";
    public static String fo = "";
    public static String fp = "Walk here";
    public static String fq = "Enter the 6-digit code generated by your";
    public static String fr = " more options";
    public static String fs = "Unable to find ";
    public static String ft = "Please try again.";
    public static String fu = "Please try using a different world.";
    public static String fv = "play this version of the game.  Please try";
    public static String fw = "Use";
    public static String fx = "Examine";
    public static String fy = "Choose Option";
    public static String fz = "authenticator app.";
    public static String ga = "M";
    public static String gb = " ";
    public static String gc = "Please remove ";
    public static String gd = "K";
    public static String ge = "Your friend list is full. Max of 200 for free users, and 400 for members";
    public static String gf = "red:";
    public static String gg = "cyan:";
    public static String gh = "Please wait...";
    public static String gi = "skill-";
    public static String gj = " from your ignore list first";
    public static String gk = "K";
    public static String gl = "yellow:";
    public static String gm = " from your friend list first";
    public static String gn = "yellow:";
    public static String go = "Your ignore list is full. Max of 100 for free users, and 400 for members";
    public static String gp = "You can't add yourself to your own ignore list";
    public static String gq = "red:";
    public static String gr = "Close";
    public static String gs = "green:";
    public static String gt = "World";
    public static String gu = "M";
    public static String gv = "Please remove ";
    public static String gw = " is already on your friend list";
    public static String gx = " is already on your ignore list";
    public static String gy = "green:";
    public static String gz = "You can't add yourself to your own friend list";
    public static String ha = "cyan:";
    public static String hb = "flash3:";
    public static String hc = "purple:";
    public static String hd = "glow2:";
    public static String he = "white:";
    public static String hf = "wave2:";
    public static String hg = "slide:";
    public static String hh = "scroll:";
    public static String hi = "wave2:";
    public static String hj = "shake:";
    public static String hk = "purple:";
    public static String hl = "glow3:";
    public static String hm = "flash2:";
    public static String hn = "flash1:";
    public static String ho = "scroll:";
    public static String hp = "glow1:";
    public static String hq = "glow2:";
    public static String hr = "glow1:";
    public static String hs = "shake:";
    public static String ht = "white:";
    public static String hu = "wave:";
    public static String hv = "flash2:";
    public static String hw = "glow3:";
    public static String hx = "flash1:";
    public static String hy = "flash3:";
    public static String hz = "wave:";
    public static String ia = "This is a <col=00ffff>Beta<col=ffffff> world.";
    public static String ib = "The Protect Item prayer will";
    public static String ic = "This is a <col=ffff00>High Risk<col=ffffff> world.";
    public static String id = "This is a <col=ff0000>PvP<col=ffffff> world.";
    public static String ie = "slide:";
    public static String if = "Enter your username/email & password.";
    public static String ig = "";
    public static String ih = "";
    public static String ii = "";
    public static String ij = "Login: ";
    public static String ik = "Password: ";
    public static String il = "Warning!";
    public static String im = "";
    public static String in = "Players can attack each other almost everywhere";
    public static String io = "not work on this world.";
    public static String ip = "Connecting to server...";
    public static String iq = "PIN: ";
    public static String ir = "";
    public static String is = "<u=ff>Can't Log In?</u>";
    public static String it = "Players can attack each other";
    public static String iu = "Your normal account will not be affected.";
    public static String iv = "Authenticator";
    public static String iw = "and the Protect Item prayer won't work.";
    public static String ix = "RuneScape is loading - please wait...";
    public static String iy = "almost everywhere.";
    public static String iz = "This is a <col=ffff00>High Risk <col=ff0000>PvP<col=ffffff> world.";
    public static String ja = "2010, this will be the creation email address.";
    public static String jb = "Recover";
    public static String jc = "Please enter your username.";
    public static String jd = "Login";
    public static String je = "(Please check your popup blocker.)";
    public static String jf = "Try again";
    public static String jg = "Cancel";
    public static String jh = "Page has opened in a new window.";
    public static String ji = "Forgotten your password?";
    public static String jj = "New User";
    public static String jk = "email address to login. Otherwise please login with your username.";
    public static String jl = "Back";
    public static String jm = "";
    public static String jn = "Hide username";
    public static String jo = "Existing User";
    public static String jp = "Forgotten your password? <col=ffffff>Click here.";
    public static String jq = "Welcome to RuneScape";
    public static String jr = "Forgotten password?";
    public static String js = "Error connecting to server.";
    public static String jt = "Username/email: ";
    public static String ju = "Remember username";
    public static String jv = "Invalid username or password.";
    public static String jw = "";
    public static String jx = "For accounts created after 24th November 2010, please use your";
    public static String jy = "";
    public static String jz = "If you created your account after November";
    public static String ka = "";
    public static String kb = "Players";
    public static String kc = "FULL";
    public static String kd = "Error connecting to server.";
    public static String ke = "You must enter a valid login to proceed. For accounts";
    public static String kg = "to connect to is offline at the moment.";
    public static String kh = "Sorry, there was an error trying to";
    public static String ki = "OFF";
    public static String kk = "created after 24th November 2010, please use your";
    public static String kl = "Please try again later.";
    public static String km = "Members only world";
    public static String kn = "Loading...";
    public static String kp = "The part of the website you are trying";
    public static String kq = "Type";
    public static String kr = "Location";
    public static String ks = "Click to switch";
    public static String kt = "Please try again later.";
    public static String ku = "";
    public static String kv = "log you in to this part of the website.";
    public static String kw = "email address. Otherwise please use your username.";
    public static String kx = "Free world";
    public static String ky = "World";
    public static String kz = "Select a world";

    public static void ao(int i) {
        while (true) {
            try {
                jd aa = jv.aj.aa(-2111008087);
                if (aa != null) {
                    aa.aq.ek(aa.an, (int) aa.fy, aa.ac, false, (byte) -64);
                } else {
                    return;
                }
            } catch (Throwable e) {
                throw ei.ac(e, "ix.ao(" + ')');
            }
        }
    }

    ix() throws Throwable {
        try {
            throw new Error();
        } catch (Throwable e) {
            throw ei.ac(e, "ix.<init>(" + ')');
        }
    }
}
