package defpackage;

public class mr implements ms {
    public static final mr aa = new mr(5, 8);
    public static final mr ab = new mr(25, 8);
    public static final mr ac = new mr(1, 3);
    public static final mr ad = new mr(24, 7);
    public static final mr ae = new mr(13, 16);
    public static final mr af = new mr(18, 8);
    public static final mr ag = new mr(22, 16);
    public static final mr ah = new mr(9, 15);
    public static final mr ai = new mr(10, 0);
    public static final mr aj = new mr(0, -2);
    public static final mr ak = new mr(6, 3);
    public static final mr al = new mr(15, 5);
    public static final mr am = new mr(12, 3);
    public static final mr an = new mr(2, 3);
    public static final mr ao = new mr(4, 8);
    public static final mr ap = new mr(7, 4);
    public static final mr aq = new mr(3, 16);
    public static final mr ar = new mr(23, 8);
    public static final mr as = new mr(14, 8);
    public static final mr at = new mr(8, 2);
    public static final mr au = new mr(19, -1);
    public static final mr av = new mr(20, 8);
    public static final mr aw = new mr(11, 2);
    public static final mr ax = new mr(17, -1);
    public static final mr ay = new mr(21, -1);
    public static final mr az = new mr(16, -1);
    public static final mr ba = new mr(42, 7);
    public static final mr bb = new mr(31, 3);
    public static final mr bc = new mr(48, 4);
    public static final mr bd = new mr(33, 1);
    public static final mr be = new mr(44, 7);
    public static final mr bf = new mr(50, 3);
    public static final mr bg = new mr(47, 7);
    public static final mr bh = new mr(28, 7);
    public static final mr bi = new mr(36, 8);
    public static final mr bj = new mr(41, 7);
    public static final mr bk = new mr(49, -1);
    public static final mr bl = new mr(51, -1);
    public static final mr bm = new mr(27, 13);
    public static final mr bn = new mr(46, 8);
    public static final mr bo = new mr(38, 2);
    public static final mr bp = new mr(26, 6);
    public static final mr bq = new mr(40, 13);
    public static final mr br = new mr(30, 10);
    public static final mr bs = new mr(37, 7);
    public static final mr bt = new mr(29, 7);
    public static final mr bu = new mr(32, 4);
    public static final mr bv = new mr(43, 0);
    public static final mr bw = new mr(45, -1);
    public static final mr bx = new mr(35, 11);
    public static final mr by = new mr(34, 3);
    public static final mr bz = new mr(39, 7);
    public static final mr ca = new mr(58, -1);
    public static final mr cb = new mr(52, 3);
    public static final mr cc = new mr(56, 8);
    public static final mr cd = new mr(73, -1);
    public static final mr ce = new mr(64, 3);
    public static final mr cf = new mr(57, 9);
    public static final mr cg = new mr(70, -2);
    public static final mr ch = new mr(65, 8);
    public static final mr ci = new mr(66, 5);
    public static final mr cj = new mr(77, -1);
    public static final mr ck = new mr(63, 8);
    public static final mr cl = new mr(54, -1);
    public static final mr cm = new mr(62, 3);
    public static final mr cn = new mr(75, 8);
    public static final mr co = new mr(55, 8);
    public static final mr cp = new mr(60, 14);
    public static final mr cq = new mr(67, 8);
    public static final mr cr = new mr(59, 0);
    public static final mr cs = new mr(71, 11);
    public static final mr ct = new mr(61, 6);
    public static final mr cu = new mr(69, 0);
    public static final mr cv = new mr(68, 8);
    public static final mr cw = new mr(74, 4);
    public static final mr cx = new mr(72, -1);
    public static final mr cy = new mr(53, 3);
    public static final mr cz = new mr(76, 9);
    public static final mr da = new mr(88, 3);
    public static final mr db = new mr(80, -2);
    public static final mr dd = new mr(86, 8);
    public static final mr de = new mr(82, 8);
    public static final mr dh = new mr(79, 13);
    public static final mr di = new mr(89, 2);
    public static final mr dj = new mr(95, 3);
    public static final mr dk = new mr(78, -1);
    public static final mr dl = new mr(81, -1);
    public static final mr do = new mr(94, 9);
    public static final mr dp = new mr(84, -1);
    public static final mr dq = new mr(92, -1);
    public static final mr dr = new mr(85, 8);
    public static final mr ds = new mr(87, 15);
    public static final mr dt = new mr(93, -1);
    public static final mr dv = new mr(91, 7);
    public static final mr dw = new mr(90, 8);
    public static final mr dx = new mr(83, 3);
    final int dm;
    final int dz;

    mr(int i, int i2) {
        try {
            this.dz = 714099029 * i;
            this.dm = 1286525731 * i2;
        } catch (Throwable e) {
            throw ei.ac(e, "mr.<init>(" + ')');
        }
    }
}
